### ISSUE TITLE
CMake clean up

### ISSUE THREAD

**Issue by gonsie** [ROSS-org/ROSS#139]
I’m creating this issue to track various CMake issues that need to be addressed. 

@caitlinross Can you tell me what version of cmake is running on the various RPI machines that should run ROSS? Amos, kratos, ...?? What about ANL machines?

At a bare minimum, I plan to:
- [x] automatically find MPI
- [x] automatically detect architecture (system processor type)
- [x] export ROSS targets in a modern CMake way (requires upgrading to v3.5)
- [x] update documentation for model developers on how to import ROSS CMake targets
- [x] update RPATH settings (currently throws a warning for Mac)

**Comment by laprej** [comment]
You may want to run your first point by Chris. I recall him having an issue with that although I can’t remember the particulars.

**Comment by caitlinross** [comment]
CMake versions:
DRP and Amos- 2.8.12, though it looks like both systems have CMake modules that can be loaded with version 3.3.2 for DRP and 3.0.0 for Amos. 
RSA is in the process of being retired.
The Power9 system has a module that's version 3.12.2
Theta (ANL) uses v 3.5.2.

As a side note, RISA (and one of its dependencies) will require v3.12, but it won't be a required part of ROSS to build.

Tagging @carothersc so he sees this. Any issues with upgrading the required version for cmake?

**Comment by gonsie** [comment]
@laprej #67 has some details on detecting MPI / the C compiler from CMake. Older versions of CMake definitely have some problems with detecting the correct compilers and MPI, but there has been a lot of development to improve things. 

In any case, we’ll have to make sure that BG/Q builds still work for any changes I make.

**Comment by caitlinross** [comment]
How important is it really to continue to support BG/Q? I'm not aware of anyone using ROSS/CODES that's used it recently.  I don't think I've used it since early 2017.  And I'm not even sure it's still really supported by CODES either since they're typically using Theta or some other Linux cluster at ANL. I remember last time I tried to get CODES to run on the BG/Q it was a huge pain to get it to even build, so that's part of why I stopped using it. Also the 16 GB of RAM per node is pretty limiting, especially for CODES models.

**Comment by caitlinross** [comment]
To add on, I think as long as we support Power9 systems, it's fine to not support our BG/Q specifically. And our Power9 system has newest CMake version out of all the systems I checked.

**Comment by gonsie** [comment]
Thanks @caitlinross. I had assumed that Amos was will still getting some use. LLNL will be turning off their open BG/Q in the next month (if I remember correctly). I’ll focus on supporting power9 with CMake v3.5 and we can always reassess later.
