### ISSUE TITLE
CMake Object Library

### ISSUE THREAD

**Issue by laprej** [ROSS-org/ROSS#152]
https://github.com/ROSS-org/ROSS/blob/6cb9316c5c0fea22dc798c9a32998a68ff7a0810/core/CMakeLists.txt#L131

Does this line add anything to our build?  It is confusing Xcode, or rather, subsequent references to `ROSS_obj` are e.g., lines [133](https://github.com/ROSS-org/ROSS/blob/6cb9316c5c0fea22dc798c9a32998a68ff7a0810/core/CMakeLists.txt#L133) and [138](https://github.com/ROSS-org/ROSS/blob/6cb9316c5c0fea22dc798c9a32998a68ff7a0810/core/CMakeLists.txt#L138).  This is documented [here](https://cmake.org/cmake/help/latest/command/add_library.html#object-libraries).

If no one has any objections, could we simply replace `$<TARGET_OBJECTS:ROSS_obj>` with `${ross_srcs}` in both line 133 and 138?

**Comment by caitlinross** [comment]
I don't have any objections, but should probably see what @gonsie says. It looks like she made that change in the build relatively recently, so maybe she has a specific reason for making that change?

**Comment by laprej** [comment]
@caitlinross agreed.  Looks like a lot has been going on in these CMake files lately!

**Comment by gonsie** [comment]
With these lines, we build the `.o` files once for both the static and shared libraries. Maybe you could try a newer version of cmake? It seem like there have been some bugs with the Xcode generator and generator expressions in the past.

**Comment by caitlinross** [comment]
Okay, so it's only because it's currently building both static and shared? In #149, it's been changed to only build one or the other and rely on Cmake to choose the correct one (based on the value of `BUILD_SHARED_LIBS`). So looks like we could go back to just a single `ADD_LIBRARY` call.

**Comment by laprej** [comment]
That sounds like a good solution as long as everyone else is happy with it.  Once that PR is merged I can go make those changes.

**Comment by gonsie** [comment]
I kind of want to build both static and shared all the time... but I guess that doesn't really make sense for how most people use ROSS (they most likely a user would not want to link to a system-provided ROSS).

**Comment by caitlinross** [comment]
I went ahead and fixed it in the new release #149 @laprej.
