### ISSUE TITLE
CODES develop integration

### ISSUE THREAD

**Issue by gonsie** [ROSS-org/ROSS#160]
The CODES master branch currently doesn't work with ROSS develop branch. Is there an "official" way we want to updates CODES? I'm unfamiliar with CODES, do they have a particular git workflow in place?

Details should be added to [the git workflow blog post](https://ross-org.github.io/ross-dev/git-branching-workflow.html)

ping @caitlinross

**Comment by nmcglohon** [comment]
CODES is in a kind of transitional period at the moment. Following the recent migration to GitHub this summer, creating an actual git workflow is something I'll be tackling this fall. We'll probably move to something like what ROSS has, though, with a Master/Release branch and a develop branch that accepts feature merges. 

I can help ensure that CODES master works with ROSS master but ensuring that CODES master works with some latest ROSS develop branch feels like it might result in a lot of intermediate CODES releases. When CODES has a develop branch, that could be made to work with the latest ROSS develop branch. I can work on that in the coming week.

**Comment by gonsie** [comment]
Everything seems to working now with CODES master and ROSS develop, I must have mucked something up on my end 😐 . That said, we should set some standard of how we name CODES branches for ROSS releases (where API changes happen).
