### ISSUE TITLE
Should we not set CC and CXX?

### ISSUE THREAD

**Issue by laprej** [ROSS-org/ROSS#67]
According to [this](http://www.cmake.org/pipermail/cmake/2011-June/045037.html) link, CMake should be able to detect (and correctly handle) any MPI details.  And I'm fairly certain the MPI wrappers are somehow stripping the address sanitizer flags because they make it through the CMake configuration phase.

**Comment by carns** [comment]
The method described  in that link probably works fine on a typical Linux workstation, but for general portability you really need to use the mpicc or mpicxx wrappers.  The Blue Gene MPI wrappers are a good example: they actually do cross compilation (for a different CPU architecture and OS) to build compute node executables.  It isn't just a matter of linking the right libraries.

What's the address sanitizer problem?  mpicc and mpicxx generally just add arguments without modifying any that were explicitly specified.
