### ISSUE TITLE
Set clock speed at build time

### ISSUE THREAD

**Issue by laprej** [ROSS-org/ROSS#80]
Why is this a runtime parameter?  Does that make sense? :)

**Comment by carothersc** [comment]
Sure - you can move between x86_64 boxes with lots of different clock rates :-).
E.g., Mastiff is only 1.6 GHZ, while Kratos is 2.3 GHz and Area51 is 3.6 GHz.

Turbo boost may throw a monkey into the wrench into timings of some things.
I did not see it on Area51 which has an i-core 7 proc...

Thanks,
Chris

----------------------------------------------------------------------------------------------
Christopher D. Carothers

Director, Center for Computational Innovations
Professor, Department of Computer Science
Rensselaer Polytechnic Institute
110 8th Street
Troy, New York 12180-3590

e-mail: chris.carothers@gmail.com
web page: www.cs.rpi.edu/~chrisc<http://www.cs.rpi.edu/%7Echrisc>
phone: (518) 276-2930<tel:%28518%29%20276-2930>
fax: (518) 276-4033<tel:%28518%29%20276-4033>
----------------------------------------------------------------------------------------------
________________________________
